package it.uninsubria.dto;

import java.io.Serializable;

/**
 * Enumeration of main cuisine types for restaurants in TheKnife system.
 * This enum contains 30 of the most common cuisine types and mirrors the SQL ENUM implementation.
 *
 * @author Lorenzo Radice, 753252, CO
 */
public enum CuisineType implements Serializable {
    AFGHAN("Afghan"),
    AFRICAN("African"),
    ALPINE("Alpine"),
    ALSATIAN("Alsatian"),
    AMERICAN("American"),
    AMERICAN_CONTEMPORARY("American Contemporary"),
    ANDALUSIAN("Andalusian"),
    APULIAN("Apulian"),
    ARGENTINIAN("Argentinian"),
    ARMENIAN("Armenian"),
    ASIAN("Asian"),
    ASIAN_CONTEMPORARY("Asian Contemporary"),
    ASIAN_INFLUENCES("Asian Influences"),
    ASIAN_AND_WESTERN("Asian and Western"),
    ASTURIAN("Asturian"),
    AUSTRALIAN_CONTEMPORARY("Australian Contemporary"),
    AUSTRIAN("Austrian"),
    BAKERY("Bakery"),
    BALINESE("Balinese"),
    BALKAN("Balkan"),
    BARBECUE("Barbecue"),
    BASQUE("Basque"),
    BAVARIAN("Bavarian"),
    BEEF("Beef"),
    BEIJING_CUISINE("Beijing Cuisine"),
    BELGIAN("Belgian"),
    BRAZILIAN("Brazilian"),
    BRETON("Breton"),
    BRITISH_CONTEMPORARY("British Contemporary"),
    BULGOGI("Bulgogi"),
    BURGUNDIAN("Burgundian"),
    BURMESE("Burmese"),
    CAJUN("Cajun"),
    CALABRIAN("Calabrian"),
    CALIFORNIAN("Californian"),
    CAMBODIAN("Cambodian"),
    CAMPANIAN("Campanian"),
    CANTONESE("Cantonese"),
    CANTONESE_ROAST_MEATS("Cantonese Roast Meats"),
    CARIBBEAN("Caribbean"),
    CASTILIAN("Castilian"),
    CATALAN("Catalan"),
    CENTRAL_ASIAN("Central Asian"),
    CHAO_ZHOU("Chao Zhou"),
    CHEESE("Cheese"),
    CHICKEN_SPECIALITIES("Chicken Specialities"),
    CHINESE("Chinese"),
    CHINESE_CONTEMPORARY("Chinese Contemporary"),
    CHIU_CHOW("Chiu Chow"),
    CHUEOTANG("Chueotang"),
    CLASSIC_CUISINE("Classic Cuisine"),
    CLASSIC_FRENCH("Classic French"),
    COLOMBIAN("Colombian"),
    CONGEE("Congee"),
    CONTEMPORARY("Contemporary"),
    CORSICAN("Corsican"),
    COUNTRY_COOKING("Country cooking"),
    CRAB_SPECIALITIES("Crab Specialities"),
    CREATIVE("Creative"),
    CREATIVE_BRITISH("Creative British"),
    CREATIVE_FRENCH("Creative French"),
    CREOLE("Creole"),
    CROATIAN("Croatian"),
    CUBAN("Cuban"),
    CUISINE("Cuisine"),
    CUISINE_FROM_ABRUZZO("Cuisine from Abruzzo"),
    CUISINE_FROM_BASILICATA("Cuisine from Basilicata"),
    CUISINE_FROM_FRANCHE_COMTE("Cuisine from Franche-Comté"),
    CUISINE_FROM_LAZIO("Cuisine from Lazio"),
    CUISINE_FROM_ROMAGNA("Cuisine from Romagna"),
    CUISINE_FROM_SOUTH_WEST_FRANCE("Cuisine from South West France"),
    CUISINE_FROM_VALTELLINA("Cuisine from Valtellina"),
    CUISINE_FROM_THE_AOSTA_VALLEY("Cuisine from the Aosta Valley"),
    CUISINE_FROM_THE_MARCHES("Cuisine from the Marches"),
    CURRY("Curry"),
    CZECH("Czech"),
    DANISH("Danish"),
    DELI("Deli"),
    DIM_SUM("Dim Sum"),
    DOGANITANG("Doganitang"),
    DONGBEI("Dongbei"),
    DUBU("Dubu"),
    DUCK_SPECIALITIES("Duck Specialities"),
    DUMPLINGS("Dumplings"),
    DWAEJI_GUKBAP("Dwaeji-gukbap"),
    EASTERN_EUROPEAN("Eastern European"),
    EGYPTIAN("Egyptian"),
    EMILIAN("Emilian"),
    EMIRATI_CUISINE("Emirati Cuisine"),
    ENGLISH("English"),
    ETHIOPIAN("Ethiopian"),
    EUROPEAN("European"),
    EUROPEAN_CONTEMPORARY("European Contemporary"),
    FARM_TO_TABLE("Farm to table"),
    FILIPINO("Filipino"),
    FINNISH("Finnish"),
    FISH_AND_CHIPS("Fish and Chips"),
    FLEMISH("Flemish"),
    FONDUE_AND_RACLETTE("Fondue and Raclette"),
    FRENCH("French"),
    FRENCH_CONTEMPORARY("French Contemporary"),
    FRIULIAN("Friulian"),
    FUGU_PUFFERFISH("Fugu / Pufferfish"),
    FUJIAN("Fujian"),
    FUSION("Fusion"),
    GALICIAN("Galician"),
    GASTROPUB("Gastropub"),
    GEJANG("Gejang"),
    GERMAN("German"),
    GOMTANG("Gomtang"),
    GREEK("Greek"),
    GRILLS("Grills"),
    HAINANESE("Hainanese"),
    HAKKANESE("Hakkanese"),
    HANG_ZHOU("Hang Zhou"),
    HOME_COOKING("Home Cooking"),
    HOTPOT("Hotpot"),
    HUAIYANG("Huaiyang"),
    HUBEI("Hubei"),
    HUI_CUISINE("Hui Cuisine"),
    HUNANESE("Hunanese"),
    HUNANESE_AND_SICHUAN("Hunanese and Sichuan"),
    HUNGARIAN("Hungarian"),
    INDIAN("Indian"),
    INDIAN_VEGETARIAN("Indian Vegetarian"),
    INDONESIAN("Indonesian"),
    INNOVATIVE("Innovative"),
    INTERNATIONAL("International"),
    IRISH("Irish"),
    ISAN("Isan"),
    ISRAELI("Israeli"),
    ITALIAN("Italian"),
    ITALIAN_CONTEMPORARY("Italian Contemporary"),
    ITALIAN_AND_JAPANESE("Italian and Japanese"),
    ITALIAN_AMERICAN("Italian-American"),
    IZAKAYA("Izakaya"),
    JAMAICAN("Jamaican"),
    JAPAN("Japan"),
    JAPANESE("Japanese"),
    JAPANESE_CONTEMPORARY("Japanese Contemporary"),
    JAPANESE_STEAKHOUSE("Japanese Steakhouse"),
    JIANGZHE("Jiangzhe"),
    JOKBAL("Jokbal"),
    KALGUKSU("Kalguksu"),
    KOREAN("Korean"),
    KOREAN_CONTEMPORARY("Korean Contemporary"),
    KUSHIAGE("Kushiage"),
    KYOTO("Kyoto"),
    LAMB_SPECIALITIES("Lamb Specialities"),
    LAO("Lao"),
    LATIN_AMERICAN("Latin American"),
    LEBANESE("Lebanese"),
    LIGURIAN("Ligurian"),
    LOMBARDIAN("Lombardian"),
    LYONNAISE("Lyonnaise"),
    MACANESE("Macanese"),
    MALAYSIAN("Malaysian"),
    MANDU("Mandu"),
    MANTUAN("Mantuan"),
    MEATS_AND_GRILLS("Meats and Grills"),
    MEATS_AND_SEAFOOD("Meats and Seafood"),
    MEDITERRANEAN_CUISINE("Mediterranean Cuisine"),
    MEMIL_GUKSU("Memil-guksu"),
    MEXICAN("Mexican"),
    MIDDLE_EASTERN("Middle Eastern"),
    MILANESE("Milanese"),
    MODERN_BRITISH("Modern British"),
    MODERN_CUISINE("Modern Cuisine"),
    MODERN_FRENCH("Modern French"),
    MOROCCAN("Moroccan"),
    NAENGMYEON("Naengmyeon"),
    NAKAGYO_KU("Nakagyo-ku"),
    NEPALI("Nepali"),
    NINGBO("Ningbo"),
    NOODLES("Noodles"),
    NOODLES_AND_CONGEE("Noodles and Congee"),
    NORTH_AFRICAN("North African"),
    NORTH_AMERICAN("North American"),
    NORTHERN_THAI("Northern Thai"),
    NORWEGIAN("Norwegian"),
    OBANZAI("Obanzai"),
    ODEN("Oden"),
    OKONOMIYAKI("Okonomiyaki"),
    ONIGIRI("Onigiri"),
    ORGANIC("Organic"),
    OYSTER_SPECIALITIES("Oyster Specialities"),
    PAKISTANI("Pakistani"),
    PERANAKAN("Peranakan"),
    PERSIAN("Persian"),
    PERUVIAN("Peruvian"),
    PIEDMONTESE("Piedmontese"),
    PIZZA("Pizza"),
    POLISH("Polish"),
    PORK("Pork"),
    PORTUGUESE("Portuguese"),
    PROVENCAL("Provençal"),
    PUERTO_RICAN("Puerto Rican"),
    RAMEN("Ramen"),
    REGIONAL_CUISINE("Regional Cuisine"),
    REGIONAL_EUROPEAN("Regional European"),
    RICE_DISHES("Rice Dishes"),
    ROMAN("Roman"),
    RUSSIAN("Russian"),
    SARDINIAN("Sardinian"),
    SAVOYARD("Savoyard"),
    SCANDINAVIAN("Scandinavian"),
    SCOTTISH("Scottish"),
    SEAFOOD("Seafood"),
    SEASONAL_CUISINE("Seasonal Cuisine"),
    SEOLLEONGTANG("Seolleongtang"),
    SHAANXI("Shaanxi"),
    SHABU_SHABU("Shabu-shabu"),
    SHANDONG("Shandong"),
    SHANGHAINESE("Shanghainese"),
    SHARING("Sharing"),
    SHELLFISH_SPECIALITIES("Shellfish Specialities"),
    SHOJIN("Shojin"),
    SHUN_TAK("Shun Tak"),
    SICHUAN("Sichuan"),
    SICILIAN("Sicilian"),
    SINGAPOREAN("Singaporean"),
    SINGAPOREAN_AND_MALAYSIAN("Singaporean and Malaysian"),
    SMALL_EATS("Small eats"),
    SMORREBROD("Smørrebrød"),
    SOBA("Soba"),
    SOUTH_AFRICAN("South African"),
    SOUTH_AMERICAN("South American"),
    SOUTH_EAST_ASIAN("South East Asian"),
    SOUTH_INDIAN("South Indian"),
    SOUTH_TYROLEAN("South Tyrolean"),
    SOUTHERN("Southern"),
    SOUTHERN_THAI("Southern Thai"),
    SPANISH("Spanish"),
    SPANISH_CONTEMPORARY("Spanish Contemporary"),
    SRI_LANKAN("Sri Lankan"),
    STEAKHOUSE("Steakhouse"),
    STREET_FOOD("Street Food"),
    SUJEBI("Sujebi"),
    SUKIYAKI("Sukiyaki"),
    SUSHI("Sushi"),
    SWABIAN("Swabian"),
    SWEDISH("Swedish"),
    SWISS("Swiss"),
    TAIWANESE("Taiwanese"),
    TAIWANESE_CONTEMPORARY("Taiwanese contemporary"),
    TAIZHOU("Taizhou"),
    TEMPURA("Tempura"),
    TEOCHEW("Teochew"),
    TEPPANYAKI("Teppanyaki"),
    TEX_MEX("Tex-Mex"),
    THAI("Thai"),
    THAI_AND_VIETNAMESE("Thai and Vietnamese"),
    THAI_CONTEMPORARY("Thai contemporary"),
    THAI_CHINESE("Thai-Chinese"),
    TIBETAN("Tibetan"),
    TONKATSU("Tonkatsu"),
    TRADITIONAL_BRITISH("Traditional British"),
    TRADITIONAL_CUISINE("Traditional Cuisine"),
    TURKISH("Turkish"),
    TUSCAN("Tuscan"),
    UDON("Udon"),
    UMBRIAN("Umbrian"),
    UNAGI_FRESHWATER_EEL("Unagi / Freshwater Eel"),
    VEGAN("Vegan"),
    VEGETARIAN("Vegetarian"),
    VENETIAN("Venetian"),
    VENEZUELAN("Venezuelan"),
    VIETNAMESE("Vietnamese"),
    VIETNAMESE_CONTEMPORARY("Vietnamese Contemporary"),
    WORLD_CUISINE("World Cuisine"),
    XIBEI("Xibei"),
    XINJIANG("Xinjiang"),
    YAKITORI("Yakitori"),
    YOSHOKU("Yoshoku"),
    YUKHOE("Yukhoe"),
    YUNNANESE("Yunnanese"),
    ZHEJIANG("Zhejiang");

    private static final long serialVersionUID = 1L;

    private final String displayName;

    /**
     * Constructor for CuisineType enum.
     *
     * @param displayName The display name for the cuisine type
     */
    CuisineType(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Gets the display name of the cuisine type.
     *
     * @return The human-readable name of the cuisine type
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Finds a CuisineType by its display name.
     *
     * @param displayName The display name to search for
     * @return The corresponding CuisineType or null if not found
     */
    public static CuisineType fromDisplayName(String displayName) {
        for (CuisineType cuisineType : values()) {
            if (cuisineType.getDisplayName().equalsIgnoreCase(displayName)) {
                return cuisineType;
            }
        }
        return null;
    }

    @Override
    public String toString() {
        return displayName;
    }
}